component: koa
name: koa-tst
app: koa-tst

inputs:
  entryFile: app.js #以您实际入口文件名为准
  src:
    src: ./19
  region: ap-guangzhou
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release